---
# https://rustup.rs/
# https://github.com/rust-lang/rustup/issues/297
# sch: https://www.google.com/search?q=rustup+unattended+install

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - gcc
    - g++
    - pkg-config
    - make
  become: true

- name: Download and run Rust installation script
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"